// scripts/tests/baseline.test.js
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { test } from 'node:test';

import { initBaselines } from '../lib/baseline.mjs';
import { tmpProject } from './helpers.js';

test('initBaselines removes a stale coverage dir BEFORE the fallow baseline', () => {
  // A leftover ./coverage would make fallow snapshot coverage-weighted CRAP.
  const p = tmpProject({ 'package.json': { name: 'x' }, 'coverage/coverage-summary.json': '{}' });
  try {
    initBaselines(p.dir, { guardrails: { fallowRatchet: true } }, () => {});
    assert.equal(existsSync(join(p.dir, 'coverage')), false);
  } finally {
    p.cleanup();
  }
});

test('initBaselines updates fallow + LOC before coverage, only for enabled guardrails', () => {
  const p = tmpProject({ 'package.json': { name: 'x' } });
  const order = [];
  const exec = (cmd, args) => order.push(`${cmd} ${args.join(' ')}`);
  try {
    initBaselines(p.dir, { guardrails: { fallowRatchet: true, locGuard: true, coverageFloors: false } }, exec);
    // Routed through the package manager (npm default) so Yarn PnP's loader is present.
    assert.deepEqual(order, [
      'npm run check:quality -- --update',
      'npm run check:loc -- --update',
    ]);
  } finally {
    p.cleanup();
  }
});

test('initBaselines does NOT re-baseline a guardrail that already has its baseline', () => {
  // Re-apply on an already-adopted repo must not reset the ratchets (which would
  // silently bless regressions accumulated since adoption).
  const p = tmpProject({
    'package.json': { name: 'x' },
    'scripts/quality-baseline.json': '{"metrics":{}}',
    'scripts/loc-baseline.json': '{"files":{}}',
  });
  const order = [];
  try {
    initBaselines(p.dir, { guardrails: { fallowRatchet: true, locGuard: true, coverageFloors: false } },
      (cmd, args) => order.push(`${cmd} ${args.join(' ')}`));
    assert.deepEqual(order, []); // both already baselined -> nothing re-run
  } finally {
    p.cleanup();
  }
});

test('initBaselines skips coverage when the generated config is already floored', () => {
  const p = tmpProject({
    'package.json': { name: 'x' },
    'jest.config.mjs': '// Generated by project-setup.\nexport default { coverageThreshold: { global: {"statements":80,"branches":50,"functions":70,"lines":80} } };\n',
  });
  const order = [];
  try {
    initBaselines(p.dir, { testFramework: 'jest', guardrails: { coverageFloors: true } },
      (cmd, args) => order.push(`${cmd} ${args.join(' ')}`));
    assert.deepEqual(order, []); // non-zero threshold -> already floored -> no re-measure
  } finally {
    p.cleanup();
  }
});

test('coverage baseline runs last and is skipped when the guardrail is off', () => {
  const p = tmpProject({ 'package.json': { name: 'x' } });
  const order = [];
  try {
    initBaselines(p.dir, { testFramework: 'jest', guardrails: { coverageFloors: true } },
      (cmd, args) => order.push(`${cmd} ${args.join(' ')}`));
    assert.equal(order[order.length - 1], 'npm run test:coverage');
  } finally {
    p.cleanup();
  }
});
