// .claude/skills/project-setup/scripts/tests/detect.test.js
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { test } from 'node:test';

import { detect, detectDefaultBranch, detectEntry, detectGithubRemote, detectPackageManager } from '../lib/detect.mjs';
import { tmpProject } from './helpers.js';

test('detectDefaultBranch reads the repo branch, falling back to main outside a repo', () => {
  const none = tmpProject({});
  const repo = tmpProject({});
  try {
    assert.equal(detectDefaultBranch(none.dir), 'main'); // no git -> fallback
    execFileSync('git', ['init', '-b', 'develop'], { cwd: repo.dir, stdio: 'ignore' });
    assert.equal(detectDefaultBranch(repo.dir), 'develop');
  } finally {
    none.cleanup();
    repo.cleanup();
  }
});

test('detectPackageManager reads the lockfile, defaults to npm', () => {
  const a = tmpProject({ 'pnpm-lock.yaml': '' });
  const b = tmpProject({});
  try {
    assert.equal(detectPackageManager(a.dir), 'pnpm');
    assert.equal(detectPackageManager(b.dir), 'npm');
  } finally {
    a.cleanup();
    b.cleanup();
  }
});

test('detect reports tooling presence from package.json', () => {
  const p = tmpProject({
    'package.json': { devDependencies: { eslint: '^9', vitest: '^2', typescript: '^5' } },
    'tsconfig.json': '{}',
  });
  try {
    const state = detect(p.dir);
    assert.equal(state.eslint, true);
    assert.equal(state.fallow, false);
    assert.equal(state.testFramework, 'vitest');
    assert.equal(state.typescript, true);
  } finally {
    p.cleanup();
  }
});

test('detectPackageManager returns bun for a bun.lock file (v1.2+ text lockfile)', () => {
  const p = tmpProject({ 'bun.lock': '' });
  try {
    assert.equal(detectPackageManager(p.dir), 'bun');
  } finally {
    p.cleanup();
  }
});

test('detectPackageManager honors package.json#packageManager before the npm fallback', () => {
  const p = tmpProject({ 'package.json': { packageManager: 'pnpm@9.1.0' } }); // no lockfile yet
  try {
    assert.equal(detectPackageManager(p.dir), 'pnpm');
  } finally {
    p.cleanup();
  }
});

test('detectGithubRemote is true only when a github remote exists', () => {
  const gh = tmpProject({ '.git/config': '[remote "origin"]\n  url = https://github.com/o/r.git\n' });
  const gl = tmpProject({ '.git/config': '[remote "origin"]\n  url = https://gitlab.com/o/r.git\n' });
  try {
    assert.equal(detectGithubRemote(gh.dir), true);
    assert.equal(detectGithubRemote(gl.dir), false);
  } finally {
    gh.cleanup();
    gl.cleanup();
  }
});

test('detectEntry returns src/main.ts when it exists, falling back to src/index.ts', () => {
  const withMain = tmpProject({ 'src/main.ts': '' });
  const empty = tmpProject({});
  try {
    assert.equal(detectEntry(withMain.dir), 'src/main.ts');
    assert.equal(detectEntry(empty.dir), 'src/index.ts');
  } finally {
    withMain.cleanup();
    empty.cleanup();
  }
});

test('detectEntry finds a JS/JSX app entrypoint, not only the .ts variant', () => {
  const jsApp = tmpProject({ 'src/app.jsx': '' });
  try {
    assert.equal(detectEntry(jsApp.dir), 'src/app.jsx');
  } finally {
    jsApp.cleanup();
  }
});

test('detectEntry matches modern module extensions (.mts/.cts/.cjs)', () => {
  const mts = tmpProject({ 'src/index.mts': '' });
  try {
    assert.equal(detectEntry(mts.dir), 'src/index.mts');
  } finally {
    mts.cleanup();
  }
});

test('detect flags an existing flat ESLint config in another extension', () => {
  const p = tmpProject({ 'eslint.config.js': 'export default [];\n' });
  try {
    assert.equal(detect(p.dir).eslintFlatConfig, true);
  } finally {
    p.cleanup();
  }
});

test('detect surfaces brownfield collision signals', () => {
  const p = tmpProject({
    'package.json': { scripts: { lint: 'eslint src' } },
    '.eslintrc.json': '{}',
    '.github/workflows/ci.yml': 'name: ci\n',
    'jest.config.js': 'module.exports = {};\n',
  });
  try {
    const s = detect(p.dir);
    assert.equal(s.scripts.lint, 'eslint src');
    assert.equal(s.legacyEslintrc, true);
    assert.equal(s.ciWorkflow, true);
    assert.equal(s.handwrittenTestConfig, true);
  } finally {
    p.cleanup();
  }
});

test("detect does not flag the engine's own marked test config as hand-written", () => {
  const p = tmpProject({ 'jest.config.mjs': '// Generated by project-setup\nexport default {};\n' });
  try {
    assert.equal(detect(p.dir).handwrittenTestConfig, false);
  } finally {
    p.cleanup();
  }
});

test('detect treats a vite.config as a hand-written test config for Vitest, not Jest', () => {
  const vitest = tmpProject({ 'package.json': { devDependencies: { vitest: '^2' } }, 'vite.config.ts': 'export default {};\n' });
  const jest = tmpProject({ 'package.json': { devDependencies: { jest: '^30' } }, 'vite.config.ts': 'export default {};\n' });
  try {
    assert.equal(detect(vitest.dir).handwrittenTestConfig, true); // vitest reads vite.config
    assert.equal(detect(jest.dir).handwrittenTestConfig, false); // jest ignores it
  } finally {
    vitest.cleanup();
    jest.cleanup();
  }
});
