#!/usr/bin/env node
/* Generated by project-setup. Advisory quality report (NOT a gate).
 * Run: npm run report  ->  quality-report.md + quality-report.json */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export function buildReport(d) {
  const actions = [];
  if (d.deadCode.total_issues > 0) actions.push(`Remove ${d.deadCode.total_issues} dead-code finding(s) (npm run quality:dead-code).`);
  if (d.dupes.clone_groups > 0) actions.push(`Dedupe ${d.dupes.clone_groups} clone group(s) (npm run quality:dupes).`);
  for (const h of d.health.hotspots) actions.push(`Refactor complexity hotspot ${h.name} (${h.file}, CRAP ${h.crap}).`);
  for (const [rule, n] of Object.entries(d.lintWarnings.byRule)) actions.push(`Burn down ${n}x lint warn: ${rule} (then promote to error).`);
  for (const h of d.locHotspots) actions.push(`Split oversized file ${h.file} (${h.loc} LOC).`);

  const lines = [
    '# Quality report',
    '',
    `**Health:** ${d.health.score} (Grade ${d.health.grade}) | **Coverage:** ${d.coverage.lines}% lines`,
    `**Dead code:** ${d.deadCode.total_issues} | **Clone groups:** ${d.dupes.clone_groups} | **Lint warnings:** ${d.lintWarnings.total}`,
    '',
    '## Act on this next',
    '',
    actions.length ? actions.map((a, i) => `${i + 1}. ${a}`).join('\n') : '_No action items — the harness is green._',
    '',
  ];
  return { markdown: lines.join('\n'), json: { ...d, actions } };
}

function fallowJson(sub) {
  try {
    return JSON.parse(execFileSync('npx', ['fallow', ...sub, '--format', 'json', '--quiet'], { encoding: 'utf8' }));
  } catch (e) {
    return JSON.parse(e.stdout || '{}'); // fallow exits non-zero when findings exist
  }
}

function main(cwd = process.cwd()) {
  // fallow puts the score/grade under `health_score`; `summary` holds counts.
  const healthJson = fallowJson(['health']);
  const hs = healthJson.health_score ?? {};
  const deadCode = fallowJson(['dead-code']).summary ?? { total_issues: 0 };
  const dupes = fallowJson(['dupes']).stats ?? { clone_groups: 0 };
  const summaryPath = join(cwd, 'coverage', 'coverage-summary.json');
  const coverage = existsSync(summaryPath)
    ? { lines: Math.floor(JSON.parse(readFileSync(summaryPath, 'utf8')).total.lines.pct) }
    : { lines: 0 };
  const data = {
    health: { score: hs.score ?? hs.maintainability ?? 0, grade: hs.grade ?? gradeFor(hs.score ?? hs.maintainability ?? 0), hotspots: (healthJson.hotspots ?? []).slice(0, 10) },
    deadCode, dupes,
    lintWarnings: { total: 0, byRule: {} }, // populated by eslint -f json in a follow-up; advisory
    locHotspots: [],
    coverage,
  };
  const { markdown, json } = buildReport(data);
  writeFileSync(join(cwd, 'quality-report.md'), markdown);
  writeFileSync(join(cwd, 'quality-report.json'), JSON.stringify(json, null, 2) + '\n');
  console.log('Wrote quality-report.md and quality-report.json');
}

function gradeFor(score) {
  const s = typeof score === 'number' ? score : 0;
  return s >= 90 ? 'A' : s >= 80 ? 'B' : s >= 70 ? 'C' : s >= 60 ? 'D' : 'F';
}

const invokedDirectly = process.argv[1] && process.argv[1].endsWith('quality-report.mjs');
if (invokedDirectly) main();
