// scripts/lib/coverage.mjs
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { loadTemplate, renderTemplate } from './templates.mjs';

const MARKER = 'Generated by project-setup';
const CONFIG = { jest: 'jest.config.mjs', vitest: 'vitest.config.mjs' };
const TEMPLATE = { jest: 'jest.config.mjs.tmpl', vitest: 'vitest.config.mjs.tmpl' };

export function floorThresholds(summary) {
  const t = summary.total;
  const f = (k) => Math.floor(t[k].pct);
  return { statements: f('statements'), branches: f('branches'), functions: f('functions'), lines: f('lines') };
}

export function applyCoverageFloor(cwd, framework) {
  const summaryPath = join(cwd, 'coverage', 'coverage-summary.json');
  const configPath = join(cwd, CONFIG[framework]);
  if (!existsSync(summaryPath) || !existsSync(configPath)) return { updated: false, reason: 'no summary/config' };
  if (!readFileSync(configPath, 'utf8').includes(MARKER)) return { updated: false, reason: 'user config' };

  const thresholds = floorThresholds(JSON.parse(readFileSync(summaryPath, 'utf8')));
  // Preserve the globs already in the generated config: if it contains js/jsx/mjs
  // the project was set up without TypeScript; otherwise default to ts/tsx.
  const existingConfig = readFileSync(configPath, 'utf8');
  const coverageGlobs = existingConfig.includes('js,jsx,mjs')
    ? 'src/**/*.{js,jsx,mjs}'
    : 'src/**/*.{ts,tsx}';
  const content = renderTemplate(loadTemplate(TEMPLATE[framework]), { coverageThreshold: JSON.stringify(thresholds), coverageGlobs });
  writeFileSync(configPath, content);
  return { updated: true, thresholds };
}
