// .claude/skills/project-setup/scripts/lib/detect.mjs
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

// index/main/app under src/ then root, each in ts/tsx/js/jsx/mjs. Covers JS-only
// apps (e.g. src/app.js, src/app.jsx) — not just the TypeScript variants — so a
// JS entrypoint isn't mis-fallen-back to src/index.ts and flagged unused.
const ENTRY_BASENAMES = ['index', 'main', 'app'];
const ENTRY_EXTS = ['ts', 'tsx', 'mts', 'cts', 'js', 'jsx', 'mjs', 'cjs'];
const ENTRY_CANDIDATES = [
  ...ENTRY_BASENAMES.flatMap((b) => ENTRY_EXTS.map((e) => `src/${b}.${e}`)),
  ...ENTRY_BASENAMES.flatMap((b) => ENTRY_EXTS.map((e) => `${b}.${e}`)),
];

export function detectEntry(cwd) {
  // A bundler `source` field wins; else the first existing common source entry; else the fallback.
  const src = readJsonSafe(join(cwd, 'package.json'))?.source;
  if (typeof src === 'string' && existsSync(join(cwd, src))) return src;
  for (const c of ENTRY_CANDIDATES) if (existsSync(join(cwd, c))) return c;
  return 'src/index.ts';
}

const ESLINTRC = ['.eslintrc', '.eslintrc.js', '.eslintrc.cjs', '.eslintrc.json', '.eslintrc.yml', '.eslintrc.yaml'];
// Flat configs in a different extension than the eslint.config.mjs we write —
// ESLint loads only one (it checks .js before .mjs), so either theirs wins (ours
// is ignored) or ours shadows theirs. Both are collisions worth reporting.
const ESLINT_FLAT = ['eslint.config.js', 'eslint.config.cjs', 'eslint.config.ts', 'eslint.config.mts', 'eslint.config.cts'];
// Per-runner config signals — kept SEPARATE so the standdown decision can be
// scoped to the resolved runner (Jest ignores vitest.config, and vice versa).
// Vitest also reads vite.config by default, so a generated vitest.config would
// override the project's plugins/aliases/setup.
const JEST_CONFIGS = ['jest.config.js', 'jest.config.ts', 'jest.config.mjs', 'jest.config.cjs', 'jest.config.json'];
const VITEST_CONFIGS = ['vitest.config.ts', 'vitest.config.js', 'vitest.config.mjs', 'vitest.config.cts', 'vitest.config.mts'];
const VITE_CONFIGS = ['vite.config.ts', 'vite.config.js', 'vite.config.mjs', 'vite.config.cts', 'vite.config.mts'];
const MARKER = 'Generated by project-setup';

function existsAny(cwd, names) {
  return names.some((n) => existsSync(join(cwd, n)));
}

// True when one of `names` exists and the engine did NOT write it (no marker) —
// a hand-written config whose thresholds we can't safely baseline.
function hasUnmarkedConfig(cwd, names) {
  for (const f of names) {
    const p = join(cwd, f);
    if (!existsSync(p)) continue;
    try {
      if (!readFileSync(p, 'utf8').includes(MARKER)) return true;
    } catch {
      return true;
    }
  }
  return false;
}

const PM_LOCKFILES = [
  ['pnpm-lock.yaml', 'pnpm'],
  ['yarn.lock', 'yarn'],
  ['bun.lock', 'bun'],   // Bun v1.2+ text lockfile (current default)
  ['bun.lockb', 'bun'],  // legacy binary lockfile
  ['package-lock.json', 'npm'],
];

const PM_NAMES = new Set(['npm', 'pnpm', 'yarn', 'bun']);

export function detectPackageManager(cwd) {
  // 1. Explicit corepack field, e.g. "packageManager": "pnpm@9.1.0" — wins even
  //    before a lockfile exists, so a first apply targets the right manager.
  const declared = readJsonSafe(join(cwd, 'package.json'))?.packageManager;
  if (typeof declared === 'string') {
    const name = declared.split('@')[0];
    if (PM_NAMES.has(name)) return name;
  }
  // 2. Lockfile.
  for (const [file, pm] of PM_LOCKFILES) {
    if (existsSync(join(cwd, file))) return pm;
  }
  // 3. Default.
  return 'npm';
}

function readJsonSafe(path) {
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    return null;
  }
}

export function detectGithubRemote(cwd) {
  // Ask git first — robust for worktrees/submodules where `.git` is a FILE
  // pointing at the real gitdir (so `.git/config` doesn't exist here).
  try {
    const url = execFileSync('git', ['config', '--get', 'remote.origin.url'], {
      cwd,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    if (url) return /github\.com/.test(url);
  } catch {
    // git missing or not a repo — fall through to the on-disk config.
  }
  const cfg = join(cwd, '.git', 'config');
  if (!existsSync(cfg)) return false;
  return /github\.com/.test(readFileSync(cfg, 'utf8'));
}

export function detectDefaultBranch(cwd) {
  // The remote's default branch, so generated CI targets the real trunk instead
  // of a hardcoded `main`. Falls back to the current branch, then `main`.
  try {
    const ref = execFileSync('git', ['rev-parse', '--abbrev-ref', 'origin/HEAD'], {
      cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    if (ref && ref !== 'origin/HEAD') return ref.replace(/^origin\//, '');
  } catch {
    // no remote HEAD ref — fall through
  }
  try {
    // symbolic-ref (not rev-parse) so it resolves on an unborn branch too.
    const cur = execFileSync('git', ['symbolic-ref', '--short', 'HEAD'], {
      cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    if (cur) return cur;
  } catch {
    // detached HEAD or not a git repo — fall through
  }
  return 'main';
}

export function detect(cwd) {
  const pkg = readJsonSafe(join(cwd, 'package.json')) ?? {};
  const deps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) };
  const has = (name) => Object.prototype.hasOwnProperty.call(deps, name);
  const testFramework = has('vitest') ? 'vitest' : has('jest') ? 'jest' : null;
  return {
    packageManager: detectPackageManager(cwd),
    typescript: has('typescript') || existsSync(join(cwd, 'tsconfig.json')),
    eslint: has('eslint'),
    fallow: has('fallow'),
    testFramework,
    git: existsSync(join(cwd, '.git')),
    github: detectGithubRemote(cwd),
    defaultBranch: detectDefaultBranch(cwd),
    entry: detectEntry(cwd),
    // Brownfield collision signals — planners turn these into user-facing notices
    // instead of silently no-op'ing on a pre-existing config/script/workflow.
    scripts: pkg.scripts ?? {},
    legacyEslintrc: existsAny(cwd, ESLINTRC),
    eslintFlatConfig: existsAny(cwd, ESLINT_FLAT),
    // The same-name config we write (skip-if-exists) — flagged only when it's the
    // user's own (no marker), so a re-apply of our generated one won't false-fire.
    eslintConfigMjs: hasUnmarkedConfig(cwd, ['eslint.config.mjs']),
    ciWorkflow: existsSync(join(cwd, '.github', 'workflows', 'ci.yml')),
    jestConfig: hasUnmarkedConfig(cwd, JEST_CONFIGS),
    vitestConfig: hasUnmarkedConfig(cwd, VITEST_CONFIGS),
    viteConfig: existsAny(cwd, VITE_CONFIGS),
    docs: {
      context: existsSync(join(cwd, 'CONTEXT.md')),
      dir: existsSync(join(cwd, 'docs')),
    },
  };
}
