// The sentinel the engine writes into every generated config/script header.
// Readers (detect, coverage) match against it to tell "engine-owned" from
// "hand-written" — keep this in lockstep with the template headers.
export const MARKER = 'Generated by project-setup';
