/** Lucide icon ids supported by Obsidian's `setIcon` (curated for pickers). */
export const LUCIDE_ICON_CATALOG: readonly string[] = [
  'alert-circle',
  'archive',
  'arrow-right',
  'book',
  'book-open',
  'bookmark',
  'bot',
  'box',
  'brain',
  'calendar',
  'check',
  'check-circle',
  'chevron-down',
  'clipboard',
  'clipboard-paste',
  'clock',
  'cloud',
  'code',
  'coffee',
  'copy',
  'database',
  'download',
  'external-link',
  'eye',
  'file',
  'file-text',
  'filter',
  'flag',
  'flame',
  'folder',
  'folder-open',
  'gift',
  'git-branch',
  'git-commit-horizontal',
  'git-fork',
  'globe',
  'hammer',
  'heart',
  'help-circle',
  'history',
  'home',
  'image',
  'inbox',
  'info',
  'key',
  'layers',
  'layout',
  'lightbulb',
  'link',
  'list',
  'list-checks',
  'loader-2',
  'lock',
  'mail',
  'map',
  'map-pin',
  'message-square',
  'mic',
  'minus',
  'moon',
  'package',
  'paperclip',
  'pause',
  'pencil',
  'play',
  'plus',
  'refresh-cw',
  'rocket',
  'rotate-ccw',
  'search',
  'settings',
  'shield',
  'sparkles',
  'square-pen',
  'square-plus',
  'star',
  'sun',
  'tag',
  'target',
  'terminal',
  'timer',
  'trash',
  'trash-2',
  'upload',
  'user',
  'users',
  'wrench',
  'x',
  'x-circle',
  'zap',
  'zoom-in',
] as const;

export function filterLucideIcons(query: string, icons: readonly string[] = LUCIDE_ICON_CATALOG): string[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) {
    return [...icons];
  }
  return icons.filter((icon) => {
    if (icon.includes(normalized)) {
      return true;
    }
    return icon.replace(/-/g, ' ').includes(normalized);
  });
}
